# Generated by Django 2.1.5 on 2019-02-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='userNickname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userPicture',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userQQ',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userSign',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
