# Generated by Django 2.1.5 on 2019-02-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190222_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAccount',
            field=models.CharField(max_length=30),
        ),
    ]
