# Generated by Django 2.1.5 on 2019-02-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190222_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='USER_upload',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True, null=True)),
                ('content', models.CharField(max_length=1000)),
                ('userPicture', models.CharField(max_length=200)),
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
