# Generated by Django 2.1.5 on 2019-02-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_replays'),
    ]

    operations = [
        migrations.AddField(
            model_name='replays',
            name='replay_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
