# Generated by Django 2.1.5 on 2019-02-26 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_replays_replay_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_upload',
            old_name='userPicture',
            new_name='Picture',
        ),
    ]
