# Generated by Django 2.1.5 on 2019-02-28 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190226_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='replays',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
