# Generated by Django 2.1.5 on 2019-03-04 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_attention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attentiond', models.CharField(max_length=30, null=True)),
                ('attentions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.AlterField(
            model_name='post_like',
            name='is_like',
            field=models.BooleanField(null=True),
        ),
    ]
